### ISSUE TITLE
FPS, resolution and PAL

### ISSUE THREAD

**Issue by mgoeller** [wooky/esp32-analog-video-over-wifi#1]
Hi

Very interested project! How many FPS and which resolution can you achieve while streaming?

Thanks

**Comment by wooky** [comment]
It should achieve the resolution provided by the decoder chip used. For instance, a 480i NTSC signal is expected to produce a 704x480 29.97FPS video stream. The important question becomes, can the ESP32 encode the stream into JPEG and send it over WiFi fast enough?

**Comment by mgoeller** [comment]
Nice. Are you interested in doing some contract work relating to this? You can text me at mailgoe@gmail.com for more details.
